# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: polestar_development
  pool: 5
  username: dbuser
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: polestar_test
  pool: 5
  username: dbuser
  password:

production:
  <<: *default
  database: db/production.sqlite3

# heroku pg:backups capture --remote production
# curl -o latest.dump `heroku pg:backups public-url --remote production`
# pg_restore --verbose --clean --no-acl --no-owner -h localhost -U cocoburg -d cocoburg_development latest.dump
# rm latest.dump
